load "#{File.dirname(__FILE__)}/../_shared/Vagrantfile.partial.pubKey.rb"

machine_ips = [
  "10.0.1.21",
  "10.0.1.22",
  "10.0.1.23",
  "10.0.1.24",
]

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  machine_ips.each do |ip|
    ip_last = ip.split(".").last
    config.vm.define "node-#{ip_last}" do |node|
      node.vm.network "private_network", ip: ip
    end
  end
end
